added scheme support

diff --git a/install-tl-ubuntu b/install-tl-ubuntu
--- a/install-tl-ubuntu
+++ b/install-tl-ubuntu
@@ -76,6 +76,7 @@ ONLY_APT_DPKG=0
 NO_APT_DPKG=0
 LOG_DIR="${MAINDIR}"
 PRETEST=0
+SCHEME=scheme-full
 
 while true
 do
@@ -85,6 +86,15 @@ do
       ;;
   -b|--no-link-ubuntu)  LINK_UBUNTU=0
       shift 1
+      ;;
+  -c|--scheme)
+      if [ -f "$2" ]; then
+        SCHEME="$( readlink -f "$2" )"
+      else
+        echo "${ERRORPREFIX}the argument to $1 must be an scheme name." >&2
+        clean_error
+      fi
+      shift 2
       ;;
   -e|--hebrew)  HEBREW=1
       shift 1
@@ -227,6 +237,7 @@ if [ "${HELP}" = "1" ]; then
                                 use FoilTeX and Noweb when installed with the command
                                 'sudo apt-get install foiltex noweb').
                                 Use this option to prevent this linking.                                \e[00m
+  -c, --scheme               \e[00;36m Install TeXlive in a specified scheme, (Default: scheme-full).   \e[00m
   -e, --hebrew               \e[00;36m Install the Hebrew font collections IvriTeX and culmus.          \e[00m
   -i, --iso FILE             \e[00;36m Install from a TeX Live ISO file. For how to download, see
                                 http://www.tug.org/texlive/acquire-iso.html                             \e[00m
@@ -610,7 +621,7 @@ while (( timesTried != timesToTry )); do
     # TLPROFILE contains both --profile and the argument. ALTERNATIVE: could use
     # two variables for TLPROFILE and have both be empty if no argument.
     if [ -z "${ISO_FILE}" ]; then
-        INSTALL_ARG="./install-tl -repository \"${TLREPO}\""
+        INSTALL_ARG="./install-tl -scheme ${SCHEME} -repository \"${TLREPO}\""
     else
         INSTALL_ARG="\"${MOUNT_ISO_DIR}/install-tl\""
     fi
